import Head from 'next/head';
import { useState, useEffect, useRef } from 'react';
import dynamic from 'next/dynamic';

// Dynamically import the 3D components to avoid SSR issues
const InterviewScene = dynamic(() => import('../components/3D/Scene'), { ssr: false });

export default function InterviewPage({ 
  jobDesc, 
  cv 
}: { 
  jobDesc?: string; 
  cv?: string; 
}) {
  const [currentQuestion, setCurrentQuestion] = useState<string>('');
  const [interviewState, setInterviewState] = useState<'idle' | 'speaking' | 'listening' | 'thinking'>('idle');
  const [conversationHistory, setConversationHistory] = useState<Array<{role: string, content: string}>>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [timeRemaining, setTimeRemaining] = useState<number>(1800); // 30 minutes
  const [micActive, setMicActive] = useState(false);
  
  // Mock initial question to simulate the beginning of the interview
  useEffect(() => {
    if (jobDesc && cv) {
      setIsLoading(false);
      setInterviewState('speaking');
      setCurrentQuestion("Hello! Welcome to your mock interview. I'm your AI interviewer today. Let me start with a quick introduction. Could you please tell me about yourself and why you're interested in this position?");
      
      // Add initial greeting to conversation history
      setConversationHistory([
        { role: 'interviewer', content: "Hello! Welcome to your mock interview. I'm your AI interviewer today. Let me start with a quick introduction. Could you please tell me about yourself and why you're interested in this position?" }
      ]);
    }
  }, [jobDesc, cv]);

  // Simulate timer countdown
  useEffect(() => {
    let timer: NodeJS.Timeout;
    if (timeRemaining > 0 && !isLoading) {
      timer = setTimeout(() => setTimeRemaining(timeRemaining - 1), 1000);
    }
    return () => clearTimeout(timer);
  }, [timeRemaining, isLoading]);

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  };

  const handleUserResponse = (response: string) => {
    // Add user response to conversation history
    const updatedHistory = [...conversationHistory, { role: 'user', content: response }];
    setConversationHistory(updatedHistory);
    
    // Change state to interviewer thinking
    setInterviewState('thinking');
    setCurrentQuestion('Thinking...');
    
    // Simulate AI processing and generating next question after delay
    setTimeout(() => {
      setInterviewState('speaking');
      // In a real implementation, this would be generated by the AI
      setCurrentQuestion("Thank you for that response. Now, could you tell me about a challenging project you've worked on and how you handled it?");
      
      // Add the new question to history
      setConversationHistory([...updatedHistory, { 
        role: 'interviewer', 
        content: "Thank you for that response. Now, could you tell me about a challenging project you've worked on and how you handled it?" 
      }]);
    }, 2000);
  };

  const toggleMicrophone = () => {
    setMicActive(!micActive);
    // In a real implementation, this would start/stop speech recognition
  };

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center">
        <div className="text-center">
          <div className="inline-block animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-indigo-600 mb-4"></div>
          <p className="text-lg text-gray-700">Initializing interview session...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="interview-container">
      <Head>
        <title>Interview Session - AI Virtual Interviewer</title>
        <meta name="description" content="AI-powered virtual interview session" />
      </Head>

      {/* Top Control Bar */}
      <div className="absolute top-0 left-0 right-0 z-10 bg-white bg-opacity-80 backdrop-blur-sm p-4 flex justify-between items-center">
        <div className="text-lg font-semibold text-gray-800">
          Interview Session
        </div>
        <div className="text-lg font-mono text-gray-700 bg-gray-100 px-3 py-1 rounded">
          {formatTime(timeRemaining)}
        </div>
        <button 
          onClick={() => window.location.href = '/feedback'}
          className="bg-red-500 hover:bg-red-600 text-white px-4 py-2 rounded-lg transition"
        >
          End Interview
        </button>
      </div>

      {/* 3D Interviewer Canvas */}
      <div className="canvas-container">
        <InterviewScene 
          interviewState={interviewState} 
          currentQuestion={currentQuestion}
        />
      </div>

      {/* Question Panel */}
      <div className="absolute right-4 top-1/2 transform -translate-y-1/2 w-1/3 max-w-md bg-white bg-opacity-90 backdrop-blur rounded-xl shadow-lg p-6">
        <div className="mb-6">
          <h2 className="text-lg font-semibold text-gray-800 mb-2">Current Question</h2>
          <div className="bg-indigo-50 p-4 rounded-lg min-h-[80px] flex items-center">
            <p className="text-gray-700">{currentQuestion || "Preparing next question..."}</p>
          </div>
        </div>

        <div className="mb-6">
          <h3 className="text-md font-medium text-gray-700 mb-2">Your Response</h3>
          <div className="relative">
            <button
              onClick={toggleMicrophone}
              className={`w-full py-3 px-4 rounded-lg flex items-center justify-center ${
                micActive 
                  ? 'bg-red-100 border-2 border-red-500' 
                  : 'bg-gray-100 hover:bg-gray-200 border border-gray-300'
              } transition`}
            >
              <span className="mr-2">
                {micActive ? (
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-red-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z" />
                  </svg>
                ) : (
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-gray-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z" />
                  </svg>
                )}
              </span>
              {micActive ? 'Listening... Click to stop' : 'Hold to Speak'}
            </button>
            {micActive && (
              <div className="absolute inset-0 bg-red-500 bg-opacity-20 rounded-lg flex items-center justify-center">
                <div className="flex space-x-1">
                  <div className="w-1 h-6 bg-red-500 rounded-full animate-pulse"></div>
                  <div className="w-1 h-8 bg-red-500 rounded-full animate-pulse delay-75"></div>
                  <div className="w-1 h-5 bg-red-500 rounded-full animate-pulse delay-100"></div>
                  <div className="w-1 h-7 bg-red-500 rounded-full animate-pulse delay-150"></div>
                  <div className="w-1 h-4 bg-red-500 rounded-full animate-pulse delay-200"></div>
                </div>
              </div>
            )}
          </div>
        </div>

        <div>
          <h3 className="text-md font-medium text-gray-700 mb-2">Conversation History</h3>
          <div className="bg-gray-50 rounded-lg p-3 max-h-40 overflow-y-auto">
            {conversationHistory.slice(-3).map((item, index) => (
              <div 
                key={index} 
                className={`p-2 mb-2 rounded ${
                  item.role === 'interviewer' 
                    ? 'bg-indigo-100 text-indigo-800' 
                    : 'bg-green-100 text-green-800'
                }`}
              >
                <div className="font-medium text-xs">
                  {item.role === 'interviewer' ? 'Interviewer:' : 'You:'}
                </div>
                <div className="text-sm truncate">{item.content}</div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Bottom Action Bar */}
      <div className="absolute bottom-4 left-1/2 transform -translate-x-1/2 w-2/3 max-w-2xl bg-white bg-opacity-90 backdrop-blur rounded-xl shadow-lg p-4">
        <div className="flex justify-between items-center">
          <div className="w-4/5">
            <input
              type="text"
              placeholder="Type your response here (or use voice input)"
              className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500"
              onKeyPress={(e) => {
                if (e.key === 'Enter') {
                  handleUserResponse((e.target as HTMLInputElement).value);
                  (e.target as HTMLInputElement).value = '';
                }
              }}
            />
          </div>
          <button
            onClick={() => {
              const input = document.querySelector('input[type="text"]') as HTMLInputElement;
              if (input && input.value.trim()) {
                handleUserResponse(input.value);
                input.value = '';
              }
            }}
            className="ml-2 bg-indigo-600 hover:bg-indigo-700 text-white p-3 rounded-lg transition"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 5l7 7-7 7M5 5l7 7-7 7" />
            </svg>
          </button>
        </div>
      </div>
    </div>
  );
}

// Server-side props fetching to handle URL parameters
export async function getServerSideProps({ query }: { query: Record<string, string> }) {
  return {
    props: {
      jobDesc: query.jobDesc || '',
      cv: query.cv || ''
    }
  };
}